services:
  - type: web
    name: shilohwatch
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: EO_API_KEY
        sync: false
      - key: EO_LIST_ID
        sync: false
